Refactors
SamparkAI/composio pull request #53
Opened 2024-05-22 14:53 UTC by angrybayblade

2024-05-24 10:01 UTC, utkarsh-dixit requested changes

2024-05-24 11:48 UTC, kaavee315 commented on composio/client/endpoints.py
> +    __repr__ = __str___
As mentioned by Codium, seems like a bug

2024-05-28 07:03 UTC, sohamganatra commented on plugins/openai/composio_openai/toolset.py
> +        from composio_openai import App, ComposioToolset
This is incorrect example and does not work. ComposioToolSet 
[S] is capital.

2024-05-28 07:03 UTC, sohamganatra commented
/review

2024-05-28 07:12 UTC, sohamganatra commented on plugins/openai/composio_openai/toolset.py
> +        actions = composio_toolset.get_tools(tools=[App.GITHUB])
Seems incorrect. It is apps=[App.Github] and not tools. May be we rename the function to get_apps??

2024-05-28 09:00 UTC, kaavee315 commented
**Viraj** Install pullflow and github auth

2024-05-28 16:15 UTC, merged